# --> check the source code for various characteristics
- src/lab01/Application/Application.ino:
    - description: Ensure that Application.ino file exists in the src/lab01/Application/ directory
      check: ConfirmFileExists
    - description: Replace the 'Add Your Names Here' prompt in the program file
      check: MatchFileFragment
      options:
        fragment: "Add Your Names Here"
        count: 0
        exact: true
    - description: Create a sufficient number of single-line comments in Application.ino
      check: CountSingleLineComments
      options:
        language: "Java"
        count: 2
        exact: false
    - description: Complete all TODOs, remove the TODO markers in the Application.ino
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Write correct 'setup' method
      check: MatchFileFragment
      options:
        fragment: "setup("
        count: 1
        exact: false
    - description: Write correct 'loop' method
      check: MatchFileFragment
      options:
        fragment: "loop("
        count: 1
        exact: false

# count number of commits in the GitHub repository
- description: Have at least a specific minimum number of commits (10) in repository
  check: CountCommits
  options:
    count: 10
